"""empty message

Revision ID: 90869c47c74c
Revises: 8c96d71e8797
Create Date: 2024-03-22 00:30:48.564075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90869c47c74c'
down_revision = '8c96d71e8797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.alter_column('longitude',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
