"""empty message

Revision ID: a0b008ae86e8
Revises: 40a4a7bb1a06
Create Date: 2024-03-14 15:14:20.850587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b008ae86e8'
down_revision = '40a4a7bb1a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('artist')

    # ### end Alembic commands ###
